### ISSUE TITLE
pyshtools conda build error: macos with python 3.7

### ISSUE THREAD

**Issue by MarkWieczorek** [conda-forge/pygmt-feedstock#23]
### Comment:

Hi, I just wanted to let you know that the pyshtools project is having a problem making a conda build with pygmt on macos/python-3.7. All the other builds work, so this is probably some sort of compatibility problem (perhaps with cartopy/gdal). Here is the output:

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=508996&view=logs&j=a3e8a21a-cf17-5483-5dfe-b752375c22e3

I note that this build tries to install pygmt 0.5 instead of the newest 0.6 (no idea why...)

In any case, unless there is a simple solution, we are just going to ignore the macos/python-3.7 build that is failing. Support for python 3.7 is being dropped by many projects, so this is not a major issue.

**Comment by MarkWieczorek** [comment]
I just realized that you are now requiring python >= 3.8 with the last version. I'm pretty sure that it is the problem, so sorry for the annoyance....

**Comment by weiji14** [comment]
Yes we have dropped Python 3.7 in PyGMT v0.6.0 (see https://github.com/GenericMappingTools/pygmt/pull/1676), following [NEP29](https://numpy.org/neps/nep-0029-deprecation_policy.html#support-table). You can see our compatibility table at https://github.com/GenericMappingTools/pygmt/tree/v0.6.1#compatibility-with-gmtpythonnumpy-versions
